name: "Renovate Config Validation"

on:
  push:
    paths:
      - renovate.json
  pull_request:
    paths:
      - renovate.json
jobs:
  renovate-config-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6

      - run: npx --yes --package renovate -- renovate-config-validator --strict
