name: "Renovate Config Validation"

permissions:
  contents: read

on:
  push:
    paths:
      - renovate.json
  pull_request:
    paths:
      - renovate.json
jobs:
  renovate-config-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: block
          allowed-endpoints: >
            nodejs.org:443
            release-assets.githubusercontent.com:443
            github.com:443
            registry.npmjs.org:443

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6

      - run: npx --yes --package renovate -- renovate-config-validator --strict
